Metrics:
    Enabled: false

Style/ParallelAssignment:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/StringLiterals:
    Enabled: false

Style/For:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/InfiniteLoop:
    Enabled: false

Style/RedundantReturn:
    Enabled: false

Style/MethodCallWithoutArgsParentheses:
    Enabled: false

Style/SlicingWithRange:
    Enabled: false

Style/Next:
    Enabled: false

Style/GuardClause:
    Enabled: false

Style/NonNilCheck:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false

Layout/ExtraSpacing:
    Enabled: false

Layout/SpaceAroundOperators:
    Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
    Enabled: false

Layout/FirstArrayElementIndentation:
    Enabled: false

Naming/RescuedExceptionsVariableName:
    Enabled: false

Lint/UselessAssignment:
    Enabled: false
